def gw_intan_amort_ins(period: str = 'LTM'):
    """Amort. Of Goodwill & Intangible Assets (Insurance)

    This item represents the amortization expense related to Goodwill and Intangible Assets.

    Args:
        period: str, default='LTM'
            FY, Q, LTM, YTD
    """
    pass

def da_ins(period: str = 'LTM'):
    """Depreciation & Amortization (Insurance)

    The sum of depreciation and amortization expenses for insurance companies.

    Args:
        period: str, default='LTM'
            FY, Q, LTM, YTD
    """
    pass

def gain_invest_rev_ins(period: str = 'LTM'):
    """Gain (Loss) on Sale of Investments (Insurance)

    Args:
        period: str, default='LTM'
            FY, Q, LTM, YTD
    """
    pass

def ins_annuity_liab(period: str = 'Q'):
    """Insurance and Annuity Liabilities

    Args:
        period: str, default='Q'
            FY, Q
    """
    pass

def int_exp_ins(period: str = 'LTM'):
    """Interest Expense, Total (Insurance)

    Args:
        period: str, default='LTM'
            FY, Q, LTM, YTD
    """
    pass

def invest_equity_pref(period: str = 'Q'):
    """Investment In Equity and Pref. Securities

    Args:
        period: str, default='Q'
            FY, Q
    """
    pass

def invest_debt(period: str = 'Q'):
    """Investment in Debt Securities

    Args:
        period: str, default='Q'
            FY, Q
    """
    pass

def mort_loans(period: str = 'Q'):
    """Mortgage Loans

    Args:
        period: str, default='Q'
            FY, Q
    """
    pass

def non_ins_exp(period: str = 'LTM'):
    """Non-Insurance Activities Expenses

    Args:
        period: str, default='LTM'
            FY, Q, LTM, YTD
    """
    pass

def non_ins_rev(period: str = 'LTM'):
    """Non-Insurance Activities Revenue

    Args:
        period: str, default='LTM'
            FY, Q, LTM, YTD
    """
    pass

def other_oper_ins(period: str = 'LTM'):
    """Other Operating Expenses (Insurance)

    Args:
        period: str, default='LTM'
            FY, Q, LTM, YTD
    """
    pass

def other_rev_suppl_ins(period: str = 'LTM'):
    """Other Revenue (Insurance)

    Args:
        period: str, default='LTM'
            FY, Q, LTM, YTD
    """
    pass

def policy_loans(period: str = 'Q'):
    """Policy Loans

    Args:
        period: str, default='Q'
            FY, Q
    """
    pass

def premiums_annuity_rev(period: str = 'LTM'):
    """Premiums and Annuity Revenue

    Args:
        period: str, default='LTM'
            FY, Q, LTM, YTD
    """
    pass

def separate_acct_assets(period: str = 'Q'):
    """Separate Account Assets

    Args:
        period: str, default='Q'
            FY, Q
    """
    pass

def separate_acct_liab(period: str = 'Q'):
    """Separate Account Liability

    Args:
        period: str, default='Q'
            FY, Q
    """
    pass

def legal_settle_ins(period: str = 'LTM'):
    """Total Legal Settlements

    Args:
        period: str, default='LTM'
            FY, Q, LTM, YTD
    """
    pass

def other_invest(period: str = 'Q'):
    """Total Other Investments

    Args:
        period: str, default='Q'
            FY, Q
    """
    pass

def total_rev_ins(period: str = 'LTM'):
    """Total Revenue (Insurance)

    This item represents the total revenue generated by the company. Adjusted for specific considerations for the Insurance industry.

    Args:
        period: str, default='LTM'
            FY, Q, LTM, YTD
    """
    pass

def unearn_premium(period: str = 'Q'):
    """Unearned Premiums

    Args:
        period: str, default='Q'
            FY, Q
    """
    pass

def unpaid_claims(period: str = 'Q'):
    """Unpaid Claims

    Args:
        period: str, default='Q'
            FY, Q
    """
    pass

